name: TOC Generator

on:
  push:
    branches:
      - main

jobs:
  generate-toc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: technote-space/toc-generator@v4
        with:
          TARGET_PATHS: README.md
